<?php 
	class input_select_duo {
		/*
		*Clase: Input auto complete
		@return: Input con varias opciones
		*/

		// Propiedades
			/*=========PRIMER MANAGE============*/
			/* 1) Spry */ 
			public $spry; 
			/* 2) Name */ 
			public $name;
			/* 3) Field id */ 
			public $id;
			/* 4) Field Name */ 
			public $field; 
			/* 5) Table */ 
			public $table; 
			/* 6) Label */ 
			public $label; 
			/* 7) Hint */ 
			public $hint; 
			/* 8) Required */ 
			public $required; 
			/* 9) Size */ 
			public $size; 
			/* 10) Tooltip */ 
			public $tooltip; 
			/* 11) Class */ 
			public $class; 
			/* 12) Action */ 
			public $action; 
			/* 13) Dato */ 
			public $data; 
			/* 14) Msg_required */ 
			public $msg_required;  
			/* 15) noManage */ 
			public $noManage;
			/*=========SEGUNDO MANAGE============*/
			/* 16) Spry */ 
			public $spry_2;
			/* 17) Name */ 
			public $name_2;
			/* 18) Field id */ 
			public $id_2;
			/* 19) Field Name */ 
			public $field_2; 
			/* 20) Table */ 
			public $table_2; 
			/* 21) Label */ 
			public $label_2; 
			/* 22) Hint */ 
			public $hint_2;
			/* 23) Tooltip */ 
			public $tooltip_2; 
			/* 24) Class */ 
			public $class_2;
			/* 25) Dato */ 
			public $data_2; 
			/* 26) Msg_required */ 
			public $msg_required_2;
			/* 27) noManage */ 
			public $noManage_2;
			/* 28) fielCommun*/
			public $fieldCommun;
	}
?>